### ISSUE TITLE
macOS: Unable to connect to any bootstrap server (when using tutorial package link).

### ISSUE THREAD

**Issue by 2075** [hoprnet/hopr-chat#25]
**Describe the bug**
after installing dependencies and running the described command from the tutorial, nothing happens. after a timeout i get the error `Unable to connect to any bootstrap server`

**To Reproduce**
on macos
- take package from tutorial page
- connectivity provided without restrictions
- install node, yarn to pinned versions
- run start-hopr-chat.command (from terminal / from finder)
- after a while, error appears.

**Expected behavior**
should connect.

**Screenshots**
<img width="619" alt="image" src="https://user-images.githubusercontent.com/1140449/90641752-e0bd5200-e231-11ea-9ea6-7c44f898a052.png">

**Desktop (please complete the following information):**

- OS: macOS
- Version 10.15.6

**Comment by jjperezaguinaga** [comment]
@2075 We sadly had a small outage (see https://status.hoprnet.org) and had no other way to redeploy our testnet servers (see https://github.com/hoprnet/hopr-devops/actions/runs/211712768). This made that the `.env` that we bundle in the release no longer works as it's looking for outdated servers.

To work around that, we created a way to fetch the bootstrap servers from our DNS (see https://github.com/hoprnet/hopr-utils/pull/31), and have updated our docs to reflect this (see https://docs.hoprnet.org/home/getting-started/hopr-chat/bootstrap-nodes).

The best way to get connected is to modify the `.env` file included in the latest release and update the bootstrap servers manually. Running the following in your terminal will throw the latest:

```
$dig -t TXT _dnsaddr.bootstrap.testnet.hoprnet.org | grep dnsaddr= | cut -d'=' -f2
/ip4/34.65.148.229/tcp/9091/p2p/16Uiu2HAmRsp3VBLcyPfTBkJYEwS47bewxWqqm4sEpJEtPBLeV93n"
/ip4/34.65.219.148/tcp/9091/p2p/16Uiu2HAkwSEiK819yvnG84pNFsqXkpFX4uiCaNSwADnmYeAfctRn"
```
(you might need to remove the `"` at the end manually).

Then, you can replace `BOOTSTRAP_SERVERS` with `/ip4/34.65.148.229/tcp/9091/p2p/16Uiu2HAmRsp3VBLcyPfTBkJYEwS47bewxWqqm4sEpJEtPBLeV93n,/ip4/34.65.219.148/tcp/9091/p2p/16Uiu2HAkwSEiK819yvnG84pNFsqXkpFX4uiCaNSwADnmYeAfctRn`. Let me know if it works!

**Comment by 2075** [comment]
nice, thanks for the heads up. could this be mitigated by delivering the .env in case of outage of an existing config with a "last known good" version from another node?

**Comment by nionis** [comment]
Hey @2075, sorry for not reaching out sooner, seems this issue has slipped through the cracks.
We have moved the development of HOPR to https://github.com/hoprnet/hoprnet.

Closing this issue as it's very old and doesn't seem relevant anymore.
