### ISSUE TITLE
ERROR: There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by ligi** [hoprnet/hopr-chat#35]
when trying to follow the instructions from the README and run yarn after checking out the repo I am getting the following:

```
~/git/hopr-chat$ yarn
ERROR: There are no scenarios; must have at least one.

```

**Comment by peterbraden** [comment]
Is this from a fresh git clone of master? It looks like the package.json is missing somehow?

**Comment by nionis** [comment]
hey @ligi, we have moved the development of HOPR to https://github.com/hoprnet/hoprnet.
Closing this issue as it's been stale for some time and we haven't seen this issue reported again.
Would love it if you can give the latest version of HOPR a spin!
