### ISSUE TITLE
Create a method to allow importing private-key and pre-image to regenerate node identity

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chat#42]
- [ ] Create method to allow importing (either via stdin or file) the required data (e.g. private key, on-chain pre-image) to regenerate the node identity.
- [ ] Publish new package w/updated verison.

**Comment by nionis** [comment]
We have decided to not implement this as it makes our system less secure, removing this from the road map but keeping it open so @jjperezaguinaga or @robertkiel can write in short _why_ we are not moving forward with this. Once done feel free to close this issue.

**Comment by nionis** [comment]
No longer relevant.
