### ISSUE TITLE
CoverBot stops responding to requests. The node does not work after installation on another PC.

### ISSUE THREAD

**Issue by AlexKlos** [hoprnet/hopr-chat#56]
At first, I installed the node on a home PC with a non-static ip. And the node worked very short. After a few hours of node downtime, I noticed that if I re-run node verification, it starts working again.
![photo_2020-09-17_22-19-08](https://user-images.githubusercontent.com/66844417/93613351-311eff80-f9ea-11ea-86d3-933f8e35e074.jpg)

Then, when I learned from you that the node needs a static ip, I installed the same node on a VPS with a static ip (just copied the hopr-chat-nodebin-windows folder). But the new node doesn't work.
![photo_2020-09-17_22-19-27](https://user-images.githubusercontent.com/66844417/93613475-5875cc80-f9ea-11ea-94ab-06e0721cf204.jpg)

And now the first node on my home PC gives the same result :(
![photo_2020-09-17_22-30-45](https://user-images.githubusercontent.com/66844417/93613536-6e838d00-f9ea-11ea-901a-6f9c7cd30326.jpg)

The first node log
[log.txt](https://github.com/hoprnet/hopr-chat/files/5246342/log.txt)

The second node log
[log.txt](https://github.com/hoprnet/hopr-chat/files/5246347/log.txt)

**Comment by AlexKlos** [comment]
This problem may not be related to migrating node to another PC.

It seems that when starting node, the includedRecipient parameter defaults to "N".
If you set the includeRecipient value to "y" every time node starts, everything works fine.

It probably makes sense to change the default value of this variable.

**Comment by nionis** [comment]
hey @AlexKlos, closing this issue since we no longer develop coverbot.
