### ISSUE TITLE
`balance` not returning result

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-chat#57]
**Describe the bug**
I am running HOPR Chat binary - v1.13.0-saentis.testnet on Ubuntu 18.04. I am typing `balance` but the app does not return anything for a long time our forever. I can type other commands like `crawl` and then eventually `balance` returns the usual output.

**To Reproduce**
This is hard to reproduce. It doesn't always happen but my node has been up for several days.

**Screenshots**
This problem seems to affect at least one other user on Discord - screenshot below:
![2020-09-19_22 00 11-1](https://user-images.githubusercontent.com/11379673/93688736-423e3e00-fac8-11ea-8122-6de42227ecae.png)

**Comment by nionis** [comment]
No longer relevant.
